stages:
  - publish
  - publish-beta

publish:
  stage: publish
  image: node:12.13.0
  script:
    - echo -e $NPM_AUTH_CONTENT >> ~/.npmrc
    - yarn config set @yunke:registry https://registry-npm.myscrm.cn/repository/yunke/
    - yarn --check-files
    - yarn publish --non-interactive --no-commit-hooks

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - package.json
      when: always
publish-beta:
  stage: publish
  image: node:12.13.0
  script:
    - echo -e $NPM_AUTH_CONTENT >> ~/.npmrc
    - yarn config set @yunke:registry https://registry-npm.myscrm.cn/repository/yunke/
    - yarn --check-files
    - yarn publish --tag=beta --non-interactive --no-commit-hooks

  rules:
    - if: '$CI_COMMIT_BRANCH == "beta"'
      changes:
        - package.json
      when: always
